name: Deploy Angular App

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 22.14.0 

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: npm run build -- --configuration=production

      - name: Deploy to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          force: true
          clean: true
          folder: dist/doctor-request # Replace with your Angular project's output folder
          token: ${{ secrets.GH_PAT }}
